#!/usr/bin/env bash
# bukio-cli — Rust test report.
# Copyright (c) 2026 Erik van Kempen.
# SPDX-License-Identifier: Apache-2.0
#
# Runs the Rust test suite (all targets) and writes test/report.md plus the
# README tests badge. Rust only by design: no node, no npm, nothing to install
# beyond a toolchain — this script must keep working after the JS tree is gone.
#
# Usage: scripts/testreport.sh   (exit 1 if anything failed)

set -uo pipefail
cd "$(dirname "$0")/.."

report=test/report.md
# Scratch, and the suite's own temp fixtures, must live OUTSIDE the repository:
# the update tests assert that a plain directory is not a git clone, and git
# happily walks up out of target/tmp into the real repo, which makes that
# directory look like a clone. /var/tmp (same filesystem as the repo, not a
# small tmpfs) is the safe place.
export TMPDIR="${BUKIO_TEST_TMPDIR:-/var/tmp}"
mkdir -p "$TMPDIR"
log=$(mktemp)
rows=$(mktemp)
trap 'rm -f "$log" "$rows"' EXIT

echo "running cargo test --release — a few minutes..." >&2
cargo test --release >"$log" 2>&1
status=$?

# cargo prints "Running <target>" followed by "test result: ok. N passed; ...".
awk '
  /^ *Running / { t=$0; sub(/^ *Running /,"",t); sub(/ \(.*$/,"",t); sub(/^unittests /,"",t); next }
  /^ *Doc-tests / { t="doc-tests" }
  /^test result:/ {
    p=f=i=0
    if (match($0, /[0-9]+ passed/))  { p=substr($0,RSTART,RLENGTH); sub(/ passed/,"",p) }
    if (match($0, /[0-9]+ failed/))  { f=substr($0,RSTART,RLENGTH); sub(/ failed/,"",f) }
    if (match($0, /[0-9]+ ignored/)) { i=substr($0,RSTART,RLENGTH); sub(/ ignored/,"",i) }
    print (t==""?"?":t) "\t" p "\t" f "\t" i; t=""
  }' "$log" >"$rows"

passed=$(awk -F'\t' '{s+=$2} END{print s+0}' "$rows")
failed=$(awk -F'\t' '{s+=$3} END{print s+0}' "$rows")
ignored=$(awk -F'\t' '{s+=$4} END{print s+0}' "$rows")

# A blocked or failed cargo run produces no "test result:" lines at all. Refuse
# to publish a bogus report (and a red badge) that looks like a real verdict.
if [ "$((passed + failed))" -eq 0 ]; then
  echo "ERROR: cargo produced no test results — nothing to report." >&2
  grep -E "^ *error|Blocking waiting for file lock|No space left" "$log" >&2 || true
  exit 2
fi
sha=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
size=$(stat -c%s target/release/bukio 2>/dev/null || stat -f%z target/release/bukio 2>/dev/null || echo 0)

if [ "$failed" -eq 0 ] && [ "$status" -eq 0 ]; then
  verdict="✅ ${passed} passing · 0 failing (${passed} tests)"
  badge="brightgreen"
else
  verdict="❌ ${passed} passing · ${failed} FAILING"
  badge="red"
fi
[ "$ignored" -gt 0 ] && verdict="$verdict · ⚠️ ${ignored} ignored"

{
  echo "# bukio-cli — test report"
  echo
  echo "**Latest run:** $(date -u '+%Y-%m-%d %H:%M:%S UTC') — ${verdict}"
  echo "**Command:** \`cargo test --release\` — Rust suite, all targets"
  echo "**Revision:** \`${sha}\` · **Binary:** \`target/release/bukio\`, ${size} bytes"
  echo
  echo "## Suites"
  echo
  echo "| Suite | Passed | Failed | Ignored |"
  echo "|-------|--------|--------|---------|"
  awk -F'\t' '{printf "| `%s` | %s | %s | %s |\n", $1, $2, $3, $4}' "$rows"
  echo "| **total** | **${passed}** | **${failed}** | **${ignored}** |"
  echo
  echo "Generated by \`scripts/testreport.sh\` — do not edit by hand."
} >"$report"

# Keep the README badge and this report from drifting apart.
sed -i -E "s#badge/tests-[0-9]+%20passing-[a-z]+#badge/tests-${passed}%20passing-${badge}#" README.md

echo "wrote $report (${passed} passed, ${failed} failed, ${ignored} ignored)" >&2
[ "$status" -eq 0 ] && [ "$failed" -eq 0 ]
