// bukio-cli — agent-first double-entry bookkeeping for SMEs.
// Copyright (c) 2026 Erik van Kempen.
// SPDX-License-Identifier: Apache-2.0
//
// Canonical command digest (mirrors src/core/canonical.js): deterministic
// sha256 over stable JSON { v, actor, cmd, args, ts, nonce }. Arrays sorted
// by canonical string, object keys sorted recursively.

use serde_json::Value;
use sha2::{Digest, Sha256};

fn sort_value(value: &Value) -> Value {
    match value {
        Value::Array(items) => {
            let mut sorted: Vec<Value> = items.iter().map(sort_value).collect();
            sorted.sort_by(|a, b| {
                let ja = serde_json::to_string(a).unwrap_or_default();
                let jb = serde_json::to_string(b).unwrap_or_default();
                ja.cmp(&jb)
            });
            Value::Array(sorted)
        }
        Value::Object(map) => {
            // serde_json with preserve_order keeps insertion order; emit sorted
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            let mut out = serde_json::Map::new();
            for k in keys {
                out.insert(k.clone(), sort_value(&map[k]));
            }
            Value::Object(out)
        }
        other => other.clone(),
    }
}

/// Compact JSON with recursively sorted keys (mirrors canonicalJson).
/// Must be byte-identical to the JS implementation — compared in tests
/// against fixtures generated from the JS side.
pub fn canonical_json(value: &Value) -> String {
    serde_json::to_string(&sort_value(value)).unwrap_or_default()
}

const EXCLUDED_ARGS: [&str; 3] = ["actor", "signKey", "json"];

/// Build the sha256 digest (hex) of the canonical command shape.
pub fn build_digest(actor: &str, cmd: &str, args: &Value, ts: &str, nonce: &str) -> String {
    let mut clean = serde_json::Map::new();
    if let Value::Object(map) = args {
        for (k, v) in map {
            if !EXCLUDED_ARGS.contains(&k.as_str()) {
                clean.insert(k.clone(), v.clone());
            }
        }
    }
    let payload = serde_json::json!({
        "v": 1,
        "actor": actor,
        "cmd": cmd,
        "args": Value::Object(clean),
        "ts": ts,
        "nonce": nonce,
    });
    let canonical = canonical_json(&payload);
    let mut hasher = Sha256::new();
    hasher.update(canonical.as_bytes());
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn sorts_keys_recursively() {
        let v = json!({"b": 1, "a": {"z": [3, {"y": 1, "x": 2}], "b": true}});
        assert_eq!(canonical_json(&v), r#"{"a":{"b":true,"z":[3,{"x":2,"y":1}]},"b":1}"#);
    }

    #[test]
    fn arrays_sort_by_canonical_string() {
        let v = json!([{"b":1,"a":2}, {"a":1}]);
        assert_eq!(canonical_json(&v), r#"[{"a":1},{"a":2,"b":1}]"#);
    }

    #[test]
    fn digest_matches_a_js_generated_fixture() {
        // fixture generated by: node -e "require('./src/core/canonical.js')..."
        // (kept in tests/fixtures/canonical_digest.json)
        let f = include_str!("tests/fixtures/canonical_digest.json");
        let f: Value = serde_json::from_str(f).unwrap();
        let digest = build_digest(
            f["actor"].as_str().unwrap(),
            f["cmd"].as_str().unwrap(),
            &f["args"],
            f["ts"].as_str().unwrap(),
            f["main_nonce"].as_str().or(f["nonce"].as_str()).unwrap(),
        );
        assert_eq!(digest, f["digest"].as_str().unwrap());
    }

    #[test]
    fn digest_excludes_identity_args() {
        let base = json!({"postings": ["1100:100.00"], "date": "2026-01-01"});
        let with_identity = json!({"postings": ["1100:100.00"], "date": "2026-01-01", "actor": "human:erik", "signKey": "/x", "json": true});
        let d1 = build_digest("human:erik", "entry add", &base, "2026-01-01T00:00:00Z", "n");
        let d2 = build_digest("human:erik", "entry add", &with_identity, "2026-01-01T00:00:00Z", "n");
        assert_eq!(d1, d2);
    }
}
